### ISSUE TITLE
Comprimir CSS

### ISSUE THREAD

**Issue by lau-luna** [lau-luna/Sportseek#19]
Una vez que se termine de resolver los Issues, se debería comprimir el código de los archivos CSS para mejorar el rendimiento.

Pasos:

1. Copiar el CSS.
2. Pegarlo en [https://csscompressor.com/](url).
3. Comprimirlo y pegarlo de vuelta al archivo.

**Comment by Luciobillions** [comment]
Ahí lo hago ![IMG-20241111-WA0014.jpg](https://github.com/user-attachments/assets/a98ee148-344b-409e-ac1a-a8947e591004)

**Comment by lau-luna** [comment]
todavia no wachin

**Comment by LucioWi** [comment]
![New Piskel-2 png (10)-1 png](https://github.com/user-attachments/assets/0411b0b3-693b-438a-9cdb-76249def3c1e)

**Comment by Luciobillions** [comment]
![download](https://github.com/user-attachments/assets/f8689db5-b189-44f2-80b9-d483a28e8891)
termino el sufrimiento

**Comment by lau-luna** [comment]
finalmente 
![image](https://github.com/user-attachments/assets/c5d60bce-0546-4923-97db-fa3a684b40f7)
