### ISSUE TITLE
Faltan imágenes de productos

### ISSUE THREAD

**Issue by lau-luna** [lau-luna/Sportseek#9]
![image](https://github.com/user-attachments/assets/97075a3b-1e02-4ae9-a403-f1a8e610238c)
### Solución:

1. Ir a [www.sportseek.great-site.net](url)
2. Descargar las imágenes faltantes.
3. Subirlas a la carpeta _imgProductos_
4. `git commit & git push origin main`

**Comment by Luciobillions** [comment]
🫡

**Comment by Luciobillions** [comment]
Colgue los productos 
![images](https://github.com/user-attachments/assets/8f65e6c7-fa95-4718-94e0-4b940a302187)
